name = "plank-server"
main = "./dist/assets/server.js"
compatibility_date = "2022-09-08"

[durable_objects]
bindings = [{name = "PLANK", class_name = "Plank"}]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Plank"]

[dev]
port = 2233
